MortgageHelper2WebMVC/Controllers/FeatureController.cs
using Microsoft.AspNet.Identity;
using MortgageHelperData;
using MortgageHelperModels;
using MortgageHelperModels.FeatureModels;
using MortgageHelperModels.RatingModels;
using MortgageHelperServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MortgageHelper2WebMVC.Controllers
{
    [Authorize]
    public class FeatureController : Controller
    {
        
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FeatureCreate model)
        {

                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                var service = CreateFeatureService();
                var rservice = CreateRatingService();

                if (service.CreateFeature(model))
                {
                // at the time a feature is created, automatically generates a rating for the property
                rservice.CreateRating(new RatingCreate { PropertyID = new ApplicationDbContext().Properties.Max(x => x.PropertyID), FeatureID = new ApplicationDbContext().Features.Max(x => x.FeatureID) });
                    return RedirectToAction("Index", "Property" );
                };

                return View(model);
            
        }

        public ActionResult Edit(int id)
        {
            var service = CreateFeatureService();
            var detail = service.GetFeaturesByPropertyID(id);
            var model = new FeatureEdit
            {
                PropertyID = detail.PropertyID,
                FeatureID = detail.FeatureID,
                DistanceFromPopulace = detail.DistanceFromPopulace,
                RoadAccess = detail.RoadAccess,
                CityWater = detail.CityWater,
                CityElectric = detail.CityElectric,
                CitySewer = detail.CitySewer,
                Internet = detail.CitySewer,
                AlternateWater = detail.AlternateWater,
                AlternateElectric = detail.AlternateElectric,
                AlternateSewage = detail.AlternateSewage,
                BodyOfWater = detail.BodyOfWater,
                NearbyBodyOfWater = detail.NearbyBodyOfWater
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, FeatureEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.PropertyID != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateFeatureService();

            if (service.UpdateFeature(model))
            {
                TempData["SaveResult"] = "Your property's featuers were updated.";
                return RedirectToAction("Index", "Property");
            }

            ModelState.AddModelError("", "Your property's features could not be updated.");
            return View(model);
        }
        private RatingService CreateRatingService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new RatingService(userId);
            return service;
        }
        private FeatureService CreateFeatureService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new FeatureService(userId);
            return service;
        }

    }
}

MortgageHelper2WebMVC/Controllers/MortgageController.cs
using Microsoft.AspNet.Identity;
using MortgageHelperModels;
using MortgageHelperModels.MortgageModels;
using MortgageHelperServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MortgageHelper2WebMVC.Controllers
{
    [Authorize]
    public class MortgageController : Controller
    {
        public ActionResult MortgageCalculator(int id)
        {
            
            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MortgageCalculator(MortgageDetail model, int id)
        {
            var svc = CreateMortgageService();
            //add new mortgage object to database with necessary properties provided by user
            svc.CreateMortgage(model, id);
            //get mortgage object that was just made
            var detail = svc.GetMortgageByPropertyID(id);
            //This section is where I convert the formulas for calculating a mortgage into code. While PEMDAS logic remains constant, the formula requires use of ^ which means something different in this language than in mathematics. To resolve this I created multiple variables to break up the formulas calculations into smaller portions. I've included the formulas below to make it easier to follow the logic. 
            /*M = monthly payment, P = principal, I = interest, N = number of payments, R = monthly interest rate
             */
            
            //interest rate comes in at values above for apr, needs to be /12 for monthly and /100 to convert to proper format
            decimal monthlyInterestRate = detail.Interest /1200;
            //convert years to months
            decimal newPeriod = detail.Period * 12;
            double y = (double)(1 + monthlyInterestRate);
            double z = (double)newPeriod;

            decimal P = detail.Price - detail.Payment;
            double var2 = (double)(newPeriod * (-1));
            decimal x = (decimal)Math.Pow(y, z);
            decimal negx = (decimal)Math.Pow( y, var2 );

            // formula  M = P [ I(1 + I)^N ] / [ (1 + I)^N – 1]
            decimal newmonthlypayment = (P * monthlyInterestRate * x) / (x - 1);
            // formula Total Amount Paid For Loan = (R*P*N) / 1-((1+R)^-N) 
            decimal newTotalLoan = (monthlyInterestRate * P * newPeriod) / (1 - negx);
            ViewBag.ResultA = newmonthlypayment;
            ViewBag.ResultB = newTotalLoan;

            //delete mortgage object that was just added to database
            svc.DeleteAllMortgagesGivenPropertyID(id);
            return View();
        }
        private MortgageService CreateMortgageService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new MortgageService(userId);
            return service;
        }
    }
}

MortgageHelper2WebMVC/Controllers/PropertyController.cs
using MortgageHelperModels;
using MortgageHelperModels.PropertyModels;
using MortgageHelperServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace MortgageHelper2WebMVC.Controllers
{
    [Authorize]
    public class PropertyController : Controller
    {
        
        public ActionResult Index()
        {
            var service = CreatePropertyService();
            var model = service.GetProperties();

            return View(model);
        }
        // GET: Property
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PropertyCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var service = CreatePropertyService();

            if (service.CreateProperty(model))
            {
                return RedirectToAction("Create", "Feature");
            };

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var service = CreateFeatureService();
            var model = service.GetAllDetailsByPropertyID(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreatePropertyService();
            var detail = service.GetPropertyByID(id);
            var model = new PropertyEdit
                {
                    PropertyID = detail.PropertyID,
                    Address = detail.Address,
                    Size = detail.Size,
                    Price = detail.Price,
                    Seller = detail.Seller,
                    TimeOnMarket = detail.TimeOnMarket,
                    PropertyType = detail.PropertyType
                };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PropertyEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.PropertyID != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreatePropertyService();

            if (service.UpdateProperty(model))
            {
                TempData["SaveResult"] = "Your property was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your property could not be updated.");
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            var service = CreatePropertyService();
            var model = service.GetPropertyByID(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteProperty(int id)
        {
            var service = CreatePropertyService();
            var fservice = CreateFeatureService();
            var rservice = CreateRatingService();
            rservice.DeleteAllRatingsGivenPropertyID(id);
            fservice.DeleteAllFeaturesGivenPropertyID(id);
            service.DeleteProperty(id);
            //feature service deletefeature
            //ratingservice delete rating
            TempData["SaveResult"] = "Your property was deleted";

            return RedirectToAction("Index");
        }

        private PropertyService CreatePropertyService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new PropertyService(userId);
            return service;
        }

        private FeatureService CreateFeatureService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new FeatureService(userId);
            return service;
        }
        private RatingService CreateRatingService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new RatingService(userId);
            return service;
        }
    }
}

MortgageHelper2WebMVC/Views/Property/Create.cshtml
@model MortgageHelperModels.PropertyModels.PropertyCreate

@{
    ViewBag.Title = "Property Create";
}
<br />
<h2>Add New Property</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <p>This page lets you start creating a new property. If you would like to create a new property, fill out the information below and click create.</p> 
        <p>Otherwise, click Back to List at the bottom of the page.</p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Size, "Acres", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Seller, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Seller, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Seller, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeOnMarket, "List Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeOnMarket, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeOnMarket, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PropertyType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PropertyType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PropertyType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MortgageHelper2WebMVC/Views/Property/Delete.cshtml
@model MortgageHelperModels.PropertyModels.PropertyDetail

@{
    ViewBag.Title = "Delete";
}
<br />
<h2>Delete</h2>

<h3>Are you sure you want to delete this property?</h3>
<div>
    @{
        var timeOnMarket = Math.Floor((DateTimeOffset.Now - Model.TimeOnMarket.Value).TotalDays);
        string x = timeOnMarket.ToString();
        string y = $"{x} Days";
    }
    <p>Deleting this property will delete all features and ratings associated with it. There is no way to recover a deleted property.</p>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.LabelFor(model => model.Size, "Acres")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Seller)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Seller)
        </dd>

        <dt>
            @Html.LabelFor(model => model.TimeOnMarket, "Time on Market")
        </dt>

        <dd>
            @Html.DisplayName(y)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PropertyType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PropertyType)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MortgageHelper2WebMVC/Views/Property/Details.cshtml
@model MortgageHelperModels.FeatureModels.AllDetailsListItem

@{
    ViewBag.Title = "Details";
}

<h2>All Property Info</h2>

<div>
    <p>This page contains information you have entered about your property. The top half has information you can change in Edit Property, the bottom half has information you can change in Edit Amenities.</p>
    <hr />
    @{
        var timeOnMarket = Math.Floor((DateTimeOffset.Now - Model.TimeOnMarket.Value).TotalDays);
        string x = timeOnMarket.ToString();
        string y = $"{x} Days";
    }

    <dl class="dl-horizontal">

        <dt>
            @Html.LabelFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.LabelFor(model => model.Size, "Acres")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

        <dt>
            @Html.LabelFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.LabelFor(model => model.Seller)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Seller)
        </dd>

        <dt>
            @Html.LabelFor(model => model.TimeOnMarket, "Time On Market")
        </dt>

        <dd>
            @Html.DisplayName(y)
        </dd>

        <dt>
            @Html.LabelFor(model => model.PropertyType, "Property Type")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PropertyType)
        </dd>
    </dl>
</div>
<hr />

<dl class="dl-horizontal">


    <dt>
        @Html.LabelFor(model => model.DistanceFromPopulace, "Miles from Population")
    </dt>

    <dd>
        @Html.DisplayFor(model => model.DistanceFromPopulace)
    </dd>

    <dt>
        @Html.LabelFor(model => model.RoadAccess, "Road Access")
    </dt>

    <dd>
        @Html.DisplayFor(model => model.RoadAccess)
    </dd>

    <dt>
        @Html.LabelFor(model => model.CityWater, "City Water")
    </dt>

    <dd>
        @Html.DisplayFor(model => model.CityWater)
    </dd>

    <dt>
        @Html.LabelFor(model => model.CityElectric, "City Electric")
    </dt>

    <dd>
        @Html.DisplayFor(model => model.CityElectric)
    </dd>

    <dt>
        @Html.LabelFor(model => model.CitySewer, "City Sewer")
    </dt>

    <dd>
        @Html.DisplayFor(model => model.CitySewer)
    </dd>

    <dt>
        @Html.LabelFor(model => model.Internet, "Internet")
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Internet)
    </dd>

    <dt>
        @Html.LabelFor(model => model.AlternateWater, "Alternate Water")
    </dt>

    <dd>
        @Html.DisplayFor(model => model.AlternateWater)
    </dd>

    <dt>
        @Html.LabelFor(model => model.AlternateElectric, "Alternate Electric")
    </dt>

    <dd>
        @Html.DisplayFor(model => model.AlternateElectric)
    </dd>

    <dt>
        @Html.LabelFor(model => model.AlternateSewage, "Alternate Sewage")
    </dt>

    <dd>
        @Html.DisplayFor(model => model.AlternateSewage)
    </dd>

    <dt>
        @Html.LabelFor(model => model.BodyOfWater, "Watersource on Property")
    </dt>

    <dd>
        @Html.DisplayFor(model => model.BodyOfWater)
    </dd>

    <dt>
        @Html.LabelFor(model => model.NearbyBodyOfWater, "Off-property Watersource")
    </dt>

    <dd>
        @Html.DisplayFor(model => model.NearbyBodyOfWater)
    </dd>

</dl>
<hr />

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

MortgageHelper2WebMVC/Views/Property/Edit.cshtml
@model MortgageHelperModels.PropertyModels.PropertyEdit

@{
    ViewBag.Title = "Property Edit";
}
<br />
<h2>Change Property Record</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <p>Here you can change any of the base information about your property. If there is no information to change, click "Back to List" at the bottom of the page.</p>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    
    @Html.HiddenFor(model => model.PropertyID)

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Size, "Acres", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Seller, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Seller, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Seller, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeOnMarket, "List Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeOnMarket, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeOnMarket, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PropertyType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PropertyType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PropertyType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

MortgageHelper2WebMVC/Views/Property/Index.cshtml
@model IEnumerable<MortgageHelperModels.PropertyListItem>

@{
    ViewBag.Title = "Index";
}
<br />
<h2>Current Properties</h2>

<p>
    @Html.ActionLink("Add New Property", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PropertyType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Size)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>

    <td>
        @Html.DisplayFor(modelItem => item.Address)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Price)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.PropertyType)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Size)
    </td>
    <td>
        @Html.ActionLink("See More", "Details", new { id = item.PropertyID }) |
        @Html.ActionLink("Calculate Mortgage Rates", "MortgageCalculator", "Mortgage", new { id = item.PropertyID }, null) |
        @Html.ActionLink("Edit Property", "Edit", new { id = item.PropertyID }) |
        @Html.ActionLink("Edit Amenities", "Edit", "Feature", new { id = item.PropertyID }, null) |
        @Html.ActionLink("Remove Property", "Delete", new { id = item.PropertyID }, null) |
    </td>
</tr>
}

</table>